services:
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Volume mapping (See the bottom for the volume definition)
      - v_data:/var/www
      # Nginx Configs mapping
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      # Nginx SSL config
      - ./nginx/ssl/certs/nginx-selfsigned.crt:/etc/nginx/ssl/certs/nginx-selfsigned.crt
      - ./nginx/ssl/private/nginx-selfsigned.key:/etc/nginx/ssl/private/nginx-selfsigned.key
      #### You could only change the blew content. ###
      # Projects mapping in Nginx
      - ~/Projects/AppSpace/myapp-apis:/var/www/myapp-apis
      - ~/Projects/AppSpace/myapp-admin:/var/www/myapp-admin
      - ~/Projects/AppSpace/myapp:/var/www/myapp
    networks:
      # See the bottom for the network definition)
      - network_app
    depends_on:
      - php80
      - php81
      - mysql
      - redis

  # PHP 8.0 Service (If you have projects are still using php80) You could edit the volume/project mapping only.
  php80:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        PHPVERSION: "8.0"
    # If you want to create different image name, you could edit it.
    image: laravel-docker/php80
    # If you want to create different container name, you could edit it.
    container_name: php80
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    user: "${UID:-33}:${GID:-33}"
    volumes:
      - v_data:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # Project Mapping, edit below
    networks:
      - network_app

  # PHP 8.1 Service (If you have projects are still using php80) You could edit the volume/project mapping only.
  php81:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        PHPVERSION: "8.1"
    # If you want to create different image name, you could edit it.
    image: laravel-docker/php81
    # If you want to create different container name, you could edit it.
    container_name: php81
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    user: "${UID:-33}:${GID:-33}"
    volumes:
      - v_data:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # Project Mapping
      - ~/Projects/AppSpace/myapp-apis:/var/www/myapp-apis
      - ~/Projects/AppSpace/myapp:/var/www/myapp
      - ~/Projects/AppSpace/myapp-admin:/var/www/myapp-admin
    networks:
      - network_app

  # PHP 8.2 Service (If you have projects are still using php80) You could edit the volume/project mapping only.
  php82:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        PHPVERSION: "8.2"
    # If you want to create different image name, you could edit it.
    image: laravel-docker/php82
    # If you want to create different container name, you could edit it.
    container_name: php82
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    user: "${UID:-33}:${GID:-33}"
    volumes:
      - v_data:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      # Project Mapping, edit below
      - ~/Projects/AppSpace/myapp-apis:/var/www/myapp-apis
      - ~/Projects/AppSpace/myapp:/var/www/myapp
      - ~/Projects/AppSpace/myapp-admin:/var/www/myapp-admin
    networks:
      - network_app

  # Mysql8.0
  # You don't need to edit the config.
  # You could edit the .env file to config the mysql environment only.
  mysql:
    image: "mysql/mysql-server:8.0"
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    env_file:
      - .env
    volumes:
      - v_mysql:/var/lib/mysql
      # The privileges config for mysql permission
      - ./mysql/privileges.sh:/docker-entrypoint-initdb.d/privileges.sh
    networks:
      - network_app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  # Redis (You don't need to edit the config.)
  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - v_redis:/data
    networks:
      - network_app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  #  # Selenium (I am using cypress, so I comment it.)
  #  selenium:
  #    image: 'selenium/standalone-chrome'
  #    container_name: "selenium"
  #    restart: unless-stopped
  #    tty: true
  #    extra_hosts:
  #      - 'host.docker.internal:host-gateway'
  #    volumes:
  #      - /dev/shm:/dev/shm
  #    networks:
  #      - network_app

  # Mailhog (You don't need to edit the config, and  )
  # I still recommend to use APIs base mail server like "MailGun" or "MailTrap" rather than the machine.
  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_MAILHOG_PORT:-1025}:1025'
      - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - network_app

# Networks config, keep all services in same network
networks:
  network_app:
    driver: bridge
    name: network_app
# Volumes config
volumes:
  v_data:
    driver: local
    name: v_data
  v_mysql:
    driver: local
    name: v_mysql
  v_redis:
    driver: local
    name: v_redis
